spring.datasource.url=jdbc:postgresql://ep-curly-mode-anfhlo5r.c-6.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_MtH8DZc4pUvg

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true