#spring.application.name=security-scanner
#
#spring.datasource.url=jdbc:postgresql://ep-curly-mode-anfhlo5r.c-6.us-east-1.aws.neon.tech/neondb
#spring.datasource.username=neondb_owner
#spring.datasource.password=${DB_PASSWORD}
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#jwt.secret=${JWT_SECRET:mySecretKey123SuperLongStringForSecurity}
#jwt.expiration=86400000
#admin.username=${ADMIN_USERNAME:admin}
#admin.password=${ADMIN_PASSWORD:admin123}
#spring.web.resources.static-locations=classpath:/static/
#
#server.port=${PORT:9292}
#spring.profiles.active=local

spring.application.name=securiscan

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET}
jwt.expiration=21600000

server.port=${PORT:9292}
server.error.include-message=never
server.error.include-stacktrace=never

spring.web.resources.static-locations=classpath:/static/

logging.level.root=WARN
logging.level.com.securityscanner=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN

spring.profiles.active=local