spring.application.name=security-scanner
spring.datasource.url=jdbc:h2:mem:MyDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=abc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
server.port=8080
