name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 13.232.44.150
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script_stop: true
          command_timeout: 30m
          debug: true
          script: |
            cd ~/security-scanner-saas
            git pull origin main
            mvn clean package -DskipTests
            sudo systemctl restart security-scanner